import Header from "@/components/header/Header";
export const metadata = {
  title: "Cur-site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        <Header/>
        {children}
        </body>
    </html>
  );
}
